#!/bin/bash
## ----------------------------------------------------------------
## Setup libvirt
### add user 'one' to group 'libvirt'
### Note: at http://wiki.libvirt.org/page/SSHSetup
### they use "sudo usermod -G libvirt -a username1" to add user to group
DLSrc=ezilla-nchc.sf.net
adduser one libvirt
adduser libvirt-qemu libvirt
### setup /var/run/libvirt folder
mkdir -p /var/run/libvirt
chown oneadmin:libvirt /var/run/libvirt
chmod g+w /var/run/libvirt
### configure libvirtd.conf
echo "unix_sock_ro_perms = \"0777\"" >> /etc/libvirt/libvirtd.conf
echo "unix_sock_dir = \"/var/run/libvirt\"" >> /etc/libvirt/libvirtd.conf
echo "kvm" >> /etc/modules
echo "kvm_amd" >> /etc/modules
echo "kvm_intel" >> /etc/modules
## ----------------------------------------------------------------
## Setup OpenNebula
## Setup SSH client Global variable
echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
## Setup SSH private key for user 'one'
su one -s /bin/bash -c "ssh-keygen -t rsa -f /home/one/.ssh/id_rsa -q -N \"\""
### ssh-copy-host for user 'one'
#### use -p to preserve permission : (X) root:root -> (O) one:one
cp -p /home/one/.ssh/id_rsa.pub /home/one/.ssh/authorized_keys
### add user 'one' to group 'cloud'
adduser one cloud
### Configure ONE_AUTH
echo "oneadmin:opennebulaadmin" > /var/lib/one/.one/one_auth
chown oneadmin:cloud /var/lib/one/.one/one_auth
### ssh-copy-host for user 'oneadmin'
cp -p /var/lib/one/.ssh/id_rsa.pub /var/lib/one/.ssh/authorized_keys
### create image pool for opennebula
mkdir -p /srv/one
chown -R oneadmin:cloud /srv/one
### add services to DRBL Server
update-rc.d opennebula defaults
## ----------------------------------------------------------------
## upgrade kernel
apt-get -y install -t squeeze-backports linux-image-2.6.38-bpo.2-amd64
## ----------------------------------------------------------------
## Setup DRBL
echo "deb http://free.nchc.org.tw/drbl-core drbl stable" > /etc/apt/sources.list.d/drbl.list
wget -q http://drbl.nchc.org.tw/GPG-KEY-DRBL -O- | apt-key add -
apt-get update
apt-get -y install drbl clonezilla mkswap-uuid partclone drbl-chntpw mkpxeinitrd-net gpxe freedos ipxe
apt-get -y autoremove --purge vim-tiny nano
## Setup initialization procedure of DRBL (drblsrv-offline and drbl-live.sh)
### ezilla script is modified from /opt/drbl/sbin/drbl-live.sh
### It is aimed to run drblsrv-offline and drblpush 
### for the first time booting in Eziila DRBL Server
wget -q http://$DLSrc/d-i/squeeze/ezilla -O /etc/init.d/ezilla
chmod a+x /etc/init.d/ezilla
update-rc.d ezilla defaults
### config network alias for DHCP server
cat >> /etc/network/interfaces << EOF
## setup eth0:1 as ethernet alias
auto eth0:1
iface eth0:1 inet static
address 10.0.0.254
netmask 255.0.0.0
EOF
### Adding support of KVM physical network sharing bridge
#### 1. patching /usr/bin/mkpxeinitrd-net
#### reference : drbl-virt 0.1.3 (http://code.google.com/p/drbl-virt)
#### http://trac.nchc.org.tw/grid/export/248/drbl-virt/sbin/drbl_bridge_kvm_patch
mv /usr/bin/mkpxeinitrd-net /usr/bin/mkpxeinitrd-net.dpkg
wget -q http://$DLSrc/d-i/squeeze/mkpxeinitrd-net -O /usr/bin/mkpxeinitrd-net
chmod a+x /usr/bin/mkpxeinitrd-net
#### 2. patching /usr/lib/mkpxeinitrd-net/initrd-skel/linuxrc-or-init
mv /usr/lib/mkpxeinitrd-net/initrd-skel/linuxrc-or-init /usr/lib/mkpxeinitrd-net/initrd-skel/linuxrc-or-init.dpkg
wget -q http://$DLSrc/d-i/squeeze/linuxrc-or-init -O /usr/lib/mkpxeinitrd-net/initrd-skel/linuxrc-or-init
chmod a+x /usr/lib/mkpxeinitrd-net/initrd-skel/linuxrc-or-init
#### 3. patch /opt/drbl/setup/files/misc/init.drbl
mv /opt/drbl/setup/files/misc/init.drbl /opt/drbl/setup/files/misc/init.drbl.dpkg
wget -q http://$DLSrc/d-i/squeeze/init.drbl -O /opt/drbl/setup/files/misc/init.drbl
chmod a+x /opt/drbl/setup/files/misc/init.drbl
## remove NIS service for the first time
## since it's not yet configured
update-rc.d -f nis remove
## remove libvirt-bin service for the first time
## since it's not yet configured and only needed by DRBL client
update-rc.d -f libvirt-bin remove
## remove DHCP and TFTP Server service for the first time 
## since we will not need it and it's not yet configured
update-rc.d -f isc-dhcp-server remove
update-rc.d -f tftpd-hpa remove
## disable exim4 service that we don't need now
update-rc.d -f exim4 remove
update-rc.d -f dbus remove
## add sysrqd to default service
echo "opennebula" > /etc/sysrqd.secret && chmod 0600 /etc/sysrqd.secret
## ----------------------------------------------------------------
## Setup initial procedure of Ezilla
#if [[ `getconf LONG_BIT` = "64" ]]; then
        wget -q http://$DLSrc/d-i/squeeze/redir.tar.gz -O /root/redir.tar.gz
		wget -q http://$DLSrc/d-i/squeeze/include.tar.gz -O /root/include.tar.gz
		wget -q http://$DLSrc/d-i/squeeze/install_xwin.sh -O /root/install_xwin.sh
#else
#        wget -q http://$DLSrc/d-i/squeeze/redir-32.tar.gz -O /root/redir.tar.gz
#		wget -q http://$DLSrc/d-i/squeeze/include-32.tar.gz -O /root/include.tar.gz
#fi
wget -q http://sourceforge.net/projects/ezilla-nchc/files/Ezilla_Fast_Installer_Debian/ezilla.tar.gz/download -O /root/ezilla.tar.gz
wget -q http://sourceforge.net/projects/ezilla-nchc/files/Ezilla_Fast_Installer_Debian/onescript.tar.gz/download -O /root/onescript.tar.gz
wget -q http://sourceforge.net/projects/ezilla-nchc/files/Ezilla_Fast_Installer_Debian/config.tar.gz/download -O /root/config.tar.gz
wget -q http://sourceforge.net/projects/ezilla-nchc/files/Ezilla_Fast_Installer_Debian/drblwp.png/download -O /opt/drbl/image/drblwp.png
### extract ezilla related program from tarball
mkdir -p /var/lib/one/tmp
tar zxvf /root/ezilla.tar.gz -C /var/www/
tar zxvf /root/include.tar.gz -C /var/www/
tar zxvf /root/onescript.tar.gz -C /srv/
tar zxvf /root/redir.tar.gz -C /opt/
tar zxvf /root/config.tar.gz -C /root/
tar zxvf /root/config.tar.gz -C /var/lib/one/tmp
chmod a+x /var/lib/one/tmp/config/addhost.sh
chmod a+x /var/lib/one/tmp/config/rc.local
chmod a+x /root/install_xwin.sh
### clean up temp files
rm /root/ezilla.tar.gz
rm /root/include.tar.gz
rm /root/onescript.tar.gz
rm /root/redir.tar.gz
rm /root/config.tar.gz
rm /var/www/index.html
### grant proper permission for web services 
chown -R www-data:www-data /var/www/
